# Generated by Django 2.2.2 on 2019-06-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('auth_status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('registered_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=20)),
                ('ratings', models.CharField(max_length=11)),
                ('registered_time', models.CharField(max_length=50)),
            ],
        ),
    ]
